language: node_js
sudo: false
services:
  - redis-server

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

before_script:
  - sudo apt-get install default-jre
  - sudo apt-get install maven
  - if [[ $TRAVIS_NODE_VERSION == "6" ]]; then export LAB_FLAGS="--leaks"; else export LAB_FLAGS=""; fi
  - npm uninstall seneca
  - npm install seneca$SENECA_VER
  - npm install quartz-http
  - cd quartz-http
  - mvn jetty:run
  - echo FLAGS:$LAB_FLAGS
  
after_script:
  - nsp check
  - npm run coverage
